service: employee-bonus-api

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: v1
  region: us-east-1

functions:
  app:
    handler: build/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
